A Spring JPA/Batch app that loads data into a postgres database on Predix. This was used to load bulk data (> 100K rows) for a Predix based app. The step1 loads data in chunks (10 rec/time); this value can be changed as required to specific needs (BatchConfiguration#114).

A Spring JPA/Batch app that loads data into a postgres database on Predix. Use schema-all.sql (in /resources) to initialize the database (DDLs) & "csv" files to load data. The code here loads 1 file with the structure defined in the reader/write (BatchConfiguration.java).

Use schema-all.sql (in /resources) to initialize the database (DDLs) & "csv" files to load data. To load > 1 file/type, include required file in the "/resources" and add them as seperate steps in BatchConfiguration.java.

Note: At this time; the batch job runs more than once (eachtime after completion); you can customize the batch runs as required.

--Referencene:
https://spring.io/guides/gs/batch-processing/
---
tags: [predix, dataload]
projects: [spring-batch, predix]
---
:spring_version: current
:spring_boot_version: 1.3.3.RELEASE
:Component: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Component.html
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-batch-processing

