---

spring:
  profiles: cloud

  datasource:
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    validation-query: SELECT 1
    validation-interval: 30000
    time-between-eviction-runs-millis: 5000
    max-active: 100
    min-idle: 10
    max-wait: 10000
    initial-size: 10
    remove-abandoned-timeout: 60
    remove-abandoned: true
    min-evictable-idle-time-millis: 30000